import { Providers } from './providers';
import { Inter } from 'next/font/google';
import Header from './components/header';
import Footer from './components/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Cortez Amarillo',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <div style={{ width: '100%', height: '5px', backgroundColor: '#FFE047' }}>
          </div>
          {children}
          <Footer />
          <div style={{ fontSize: '10px', width: '100%', height: '30px', backgroundColor: '#F5C71A' }}>
            <p>Terminos y condiciones</p>
          </div>
        </Providers>
      </body>
    </html>
  )
}
