import { Providers } from './providers'
import { HeaderNav } from "./components/HeaderNav";

export const metadata = {
  title: "Cortez Amarillo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <HeaderNav />
          {children}
        </Providers>
      </body>
    </html>
  );
}
